version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.1
  - dependency-name: github-pages
    versions:
    - "211"
