title: /path/to/file
email: path.to.file[at]gmail[dot]com
description: PatH infosec blog
baseurl: ""
url: "https://pathtofile.run"
twitter_username: pathtofile
github_username:  pathtofile

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
